#version: '3.8'

services:
  web:
    build: .
    ports:
      - "8002:8002"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
    command: >
      sh -c "cd nexus_app &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8002"