# Generated by Django 5.2.5 on 2025-08-14 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='valor_orcamento',
        ),
    ]
