# Generated by Django 5.2.5 on 2025-08-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_remove_produto_preco_remove_projeto_valor_orcamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projeto',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
