# Generated by Django 5.2.5 on 2025-08-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_projeto_concluido_projeto_data_conclusao'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='aprovacao',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=10),
        ),
        migrations.AddField(
            model_name='projeto',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='motivo_rejeicao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
